targets:
  $default:
    builders:
      json_serializable|json_serializable:
        enabled: true
        generate_for:
          - "lib/model/product/product.dart"
          - "lib/model/store/store.dart"
      freezed:
        enabled: true
        generate_for:
          - "lib/model/product/product.dart"
          - "lib/model/store/store.dart"